apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adamlehman2018@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    cert-manager.io/issuer: "cert-issuer"
    nginx.org/websocket-services: "cluster-ip-service"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - adam-website.com
    secretName: cert-secret
  rules:
  - host: adam-website.com
    http:
      paths:
      - backend:
          service:
            name: cluster-ip-service
            port:
              number: 8082
        path: /api/go/
        pathType: Prefix
      - backend:
          service:
            name: cluster-ip-service
            port:
              number: 80
        path: /
        pathType: Prefix